[build]
	publish = "_site"
	command = "npm run build"

[[redirects]]
  from = "/feed"
  to = "https://ldstephens.net/feed/feed.xml"
  status = 301

[[redirects]]
  from = "/feed.xml"
  to = "https://ldstephens.net/feed/feed.xml"
  status = 301

[[redirects]]
  from = "/2016/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2017/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2018/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2019/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2020/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2021/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2022/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2023/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/2024/:month/:day/:slug/"
  to = "/blog/:slug/"
  status = 301
  force = true
